[package]
name = "spotify-tui-rs"
version = "0.1.5"
edition = "2021"

[[bin]]
name = "spotify-tui-rs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
crossterm = "0.27"
dirs = "5.0"
ratatui = "0.27"
rand = "0.8"
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tiny_http = "0.12"
url = "2"
